version: '3.5'

services:
  train:
    container_name: train
    build:
      context: ./train
      dockerfile: Dockerfile
    command: su -m app_user -c "python manage.py run -h 0.0.0.0"
    ports:
      - 5001:5000
    env_file:
      - ./.env.train
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:5.0.7
    hostname: redis

  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    env_file:
      - ./.env.db

  headquarter:
    container_name: headquarter
    build:
      context: ./headquarter
      dockerfile: Dockerfile
    hostname: headquarter
    command: su -m app_user -c "celery -A manage.celery_app worker --loglevel=info"
    env_file:
      - ./.env.headquarter
    depends_on:
      - redis
      - gatekeeper

  gatekeeper:
    container_name: gatekeeper
    build:
      context: ./gatekeeper
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    hostname: gatekeeper
    command: su -m app_user -c "python manage.py run -h 0.0.0.0"
    env_file:
      - ./.env.gatekeeper
    depends_on:
      - db
