version: '3.5'

services:

  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    env_file:
      - ./.env.db

  train_beat:
    container_name: train-beat
    build:
      context: ./train
      dockerfile: Dockerfile
    command: su -m app_user -c "celery -A train.app.beat:celery beat --loglevel=info --pidfile /tmp/celerybeat.pid -s /tmp/celerybeat-schedule"
    ports:
      - 5004:5000
    env_file:
      - ./.env.train
    depends_on:
      - redis_train

  train_worker:
    container_name: train-worker
    build:
      context: ./train
      dockerfile: Dockerfile
    command: su -m app_user -c "celery -A train.app.beat:celery worker --loglevel=info"
    ports:
      - 5002:5000
    env_file:
      - ./.env.train
    depends_on:
      - redis_train

  redis_train:
    container_name: redis-train
    image: redis:5.0.7
    hostname: redis_train

  headquarter:
    container_name: headquarter
    build:
      context: ./headquarter
      dockerfile: Dockerfile
    hostname: headquarter
    command: su -m app_user -c "celery -A headquarter.app.worker.handler:worker worker -P threads --loglevel=info"
    ports:
      - 5003:5000
    env_file:
      - ./.env.headquarter
    depends_on:
      - redis_headquarter

  redis_headquarter:
    container_name: redis-headquarter
    image: redis:5.0.7
    hostname: redis_headquarter

  gatekeeper:
    container_name: gatekeeper
    build:
      context: ./gatekeeper
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    hostname: gatekeeper
    command: su -m app_user -c "python manage.py run -h 0.0.0.0"
    env_file:
      - ./.env.gatekeeper
    depends_on:
      - db
