version: '3.5'

services:
  train:
    container_name: train
    build:
      context: ./train
      dockerfile: Dockerfile
    command: python manage.py run -h 0.0.0.0
    ports:
      - 5000:5000
    env_file:
      - ./.env.train
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:5.0.5
    hostname: redis

  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    env_file:
      - ./.env.db
