"""empty message

Revision ID: 1765140d2061
Revises: 
Create Date: 2020-02-26 17:55:29.914126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1765140d2061'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('barrier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['barrier_id'], ['barriers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barrier_id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stations')
    op.drop_table('barriers')
    # ### end Alembic commands ###
