"""empty message

Revision ID: 3004b56a323c
Revises: 
Create Date: 2020-02-24 21:30:30.695417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3004b56a323c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barrier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('barrier_status',
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('barrier_id', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['barrier_id'], ['barrier.id'], ),
    sa.PrimaryKeyConstraint('barrier_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('barrier_status')
    op.drop_table('barrier')
    # ### end Alembic commands ###
